# This file is sourced from .bashrc and contains all bash aliases

alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"
alias prod_back="ssh lcub-str0001"
alias prod_front="ssh lcub-fe0001"
#alias vimopen="vim $(git status | grep modified | awk '{print $3}')"
