#This file is sourced from .bashrc and contains all bash aliases

# General purposes aliases
alias aliases="vim ~/.bash_aliases"
alias ll="ls -lah"

# Bash function for making a directory and going there immediately
mcd () {
  mkdir -p $1
  cd $1
}

# Copy id_rsa.pub public key contents to clipboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"

# Vagrant shortcuts
alias vs="vagrant status"
alias vr="vagrant reload"

# Logikcull shortcuts
alias lab="cd ~/logikcull/apps/backend"
alias laf="cd ~/logikcull/apps/frontend"
alias lid="cd ~/logikcull/infra/deploy"
