# This file is sourced from .bash_profile

# Tab completion scripts
source ~/dotfiles/bash/bash_completion.d/git-completion.bash
source ~/dotfiles/bash/bash_completion.d/git-prompt.sh 
source ~/dotfiles/bash/bash_completion.d/tmux
source ~/dotfiles/bash/bash_completion.d/cap-completion.bash

# Set up aliases
source ~/dotfiles/bash/bash_aliases

# Set up bashmarks for easy directory navigation
# source ~/.local/bin/bashmarks.sh

# Show git branch in status line
export PS1='[\h: \w]$(__git_ps1 " (%s)")\$ '
export PROMPT_COMMAND='echo -ne "\033]0;${PWD/#$HOME/~}\007"'

# Add rvm to PATH for scripting support
#PATH=$PATH:$HOME/.rvm/bin
