#This file is sourced from .bashrc and contains all bash aliases

# General purposes aliases
alias aliases="vim ~/.bash_aliases"
alias ll="ls -lah"

# Bash function for making a directory and going there immediately
mcd () {
  mkdir -p $1
  cd $1
}

# Copy id_rsa.pub public key contents to clipboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"

# Vagrant shortcuts
alias lcv="cd ~/logikcull/vagrant"
alias vs="vagrant status"
alias vr="vagrant reload"
alias dev="ssh devbox"

# Logikcull shortcuts
alias be="cd ~/backend"
alias fe="cd ~/frontend"
alias dp="cd ~/deploy"

