# This file is sourced from .bash_profile

# Tab completion scripts
source ~/dotfiles/bash/bash_completion.d/git-completion.bash
source ~/dotfiles/bash/bash_completion.d/git-prompt.sh 
source ~/dotfiles/bash/bash_completion.d/tmux

# Set up aliases
source ~/dotfiles/bash/bash_aliases

# Show git branch in status line
export PS1='[\w]$(__git_ps1 " (%s)")\$ '
export PROMPT_COMMAND='echo -ne "\033]0;${PWD/#$HOME/~}\007"'

# Add rvm to PATH for scripting support
#PATH=$PATH:$HOME/.rvm/bin
