# Source the .bashrc file if it exists
if [ -f ~/.bashrc ]; then . ~/.bashrc; fi

# Setup the PATH Environment variable
export PATH=/usr/local/bin:/usr/bin:/usr/local/packer:/bin:/usr/sbin:/sbin:/usr/X11/bin:/Developer/usr/bin/:$PATH

if [ which rbenv > /dev/null]
then
  eval "$(rbenv init -)"
else
  # RVM configurations added per installation instructions
  export CC=gcc-4.2 
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function
fi
